spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=ordersdb;trustServerCertificate=true
    username: rober
    password: superhardpass12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: orders
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
