spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=ordersdb;trustServerCertificate=true
    username: rober
    password: superhardpass12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: orders
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    circuit-breaker-events:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
resilience4j:
  time-limiter:
    instances:
      inventory:
        timeout-duration: 3s

  circuit-breaker:
    instances:
      inventory:
        - register-health-indicator: true
        - event-consumer-buffer-size: 10
        - sliding-window-type: count_based
        - sliding-window-size: 5 # after 5 failed request change state
        - failure-rate-threshold: 50 # when 50% of request fail change state
        - wait-duration-in-open-state: 5s # how much time it will wait in ope state
        - permitted-number-of-calls-in-half-open-state: 3
        - automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s




