
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/products/**
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/orders/**
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**
        - id: customers
          uri: lb://customers
          predicates:
            - Path=/customers/**
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/realms/microservices-realm

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            - trace
            - route:
                RouteDefinitionLocator: info

