spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=productsdb;trustServerCertificate=true
    username: rober
    password: superhardpass12
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: products
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
